// ============================================================================
// File: BlogRequest.cs
// Author: Utkarsh Tripathi
// Created On: 16-Aug-2025
// Description: Model class representing the request for AI-based blog generation.
// ============================================================================

using System.ComponentModel.DataAnnotations;

namespace AI_Blog_Generator.Models
{
    /// <summary>
    /// Represents a request for generating a blog using AI.
    /// Contains input fields such as topic, tone, language, and word count.
    /// </summary>
    public class BlogRequest
    {
        // The main topic of the blog.
        [Required(ErrorMessage = "Topic is required.")]
        [StringLength(250, ErrorMessage = "Topic cannot be longer than 250 characters.")]
        public string Topic { get; set; }

        // The desired tone of the blog (Casual, Formal, or Humorous).
        [Required(ErrorMessage = "Tone is required.")]
        [RegularExpression("Casual|Formal|Humorous", ErrorMessage = "Tone must be Casual, Formal, or Humorous.")]
        public string Tone { get; set; }

        // The language in which the blog should be generated.
        [Required(ErrorMessage = "Language is required.")]
        [StringLength(100, ErrorMessage = "Language cannot be longer than 100 characters.")]
        public string Language { get; set; }

        // The desired word count for the generated blog. Must be between 100 and 10000.
        [Required(ErrorMessage = "Word count is required.")]
        [Range(100, 10000, ErrorMessage = "Word count must be between 100 and 10000.")]
        public int WordCount { get; set; }

        // The blog content generated by AI (output field).
        public string? GeneratedBlog { get; set; }
    }
}
